{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-actuator-autoconfigure",
    "version": "4.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-actuator",
          "version": {
            "requires": "4.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-actuator-autoconfigure-4.0.6.jar",
          "url": "spring-boot-actuator-autoconfigure-4.0.6.jar",
          "size": 141093,
          "sha512": "00fba44073c46f33124f061e95a3011ff746fbfaf3c00d2355b67cc78a3c09034712efc6d05fd64f2e589e72c1b5ff602d7c36b082a1502f867e988d2511e9ff",
          "sha256": "d2b798d02d31fbe20dfa128f561e79dbc96a460a67e0b69aaed1e07826738c02",
          "sha1": "bdd2d4f29031aa35993dbe6425b1092913aac531",
          "md5": "7d6a2868d7e51301f1b9eec181522313"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-actuator",
          "version": {
            "requires": "4.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-actuator-autoconfigure-4.0.6.jar",
          "url": "spring-boot-actuator-autoconfigure-4.0.6.jar",
          "size": 141093,
          "sha512": "00fba44073c46f33124f061e95a3011ff746fbfaf3c00d2355b67cc78a3c09034712efc6d05fd64f2e589e72c1b5ff602d7c36b082a1502f867e988d2511e9ff",
          "sha256": "d2b798d02d31fbe20dfa128f561e79dbc96a460a67e0b69aaed1e07826738c02",
          "sha1": "bdd2d4f29031aa35993dbe6425b1092913aac531",
          "md5": "7d6a2868d7e51301f1b9eec181522313"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-actuator-autoconfigure-4.0.6-javadoc.jar",
          "url": "spring-boot-actuator-autoconfigure-4.0.6-javadoc.jar",
          "size": 374658,
          "sha512": "843f15cbac1f0da309b7f96e88d0cb39b23fc493b92e875e9f73f8219ed483330267e075ea1bc231c0b8708e6322494abd30d6639523a4334374f88617efa5a7",
          "sha256": "a00939f4b2c7d3693054287d180690fbe2b60bc7bb7596152624d7fcffe00696",
          "sha1": "24dfaabb31885d3add292e5edb4a2800833d0c9d",
          "md5": "c308d5b0216586b302f40f086be7f3e2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-actuator-autoconfigure-4.0.6-sources.jar",
          "url": "spring-boot-actuator-autoconfigure-4.0.6-sources.jar",
          "size": 107643,
          "sha512": "9085643978f644b11b07d3a1710f345a7b58395fd988b26d66f076f215ca08a636e594abe1a6051e23eb81b87dc7b42a4e5a4c68d74ad6468a4098b076d5d276",
          "sha256": "d973e83c266d7cd7ada84e1bb1196e309b530ae2e60c9493cbb9a59c5fdb1541",
          "sha1": "f808f8d8c2e789d74ff9431d9a7fca0b5a2c1f2a",
          "md5": "530d49cb67f26a9b2bc0fad83250e7d0"
        }
      ]
    }
  ]
}
