{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-core",
    "version": "7.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-core-7.0.7.jar",
          "url": "spring-core-7.0.7.jar",
          "size": 2032909,
          "sha512": "fa57d61f0ba870a257816b1453111eb09a171a9e65f0c7711617624e815114e3b0829687b820480101f3b5900a84f0204b91d853c7aeaaebe98ad63fa907f51f",
          "sha256": "9e1c13ed6d69002aae7ebc4b7d2d1d07e309013a2fbb63ab266bea8601229785",
          "sha1": "4f85340fd463031cd93a0629a0323bb467ae51aa",
          "md5": "33ce0cb6c81faaa067b4b05dcd152188"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-core-7.0.7.jar",
          "url": "spring-core-7.0.7.jar",
          "size": 2032909,
          "sha512": "fa57d61f0ba870a257816b1453111eb09a171a9e65f0c7711617624e815114e3b0829687b820480101f3b5900a84f0204b91d853c7aeaaebe98ad63fa907f51f",
          "sha256": "9e1c13ed6d69002aae7ebc4b7d2d1d07e309013a2fbb63ab266bea8601229785",
          "sha1": "4f85340fd463031cd93a0629a0323bb467ae51aa",
          "md5": "33ce0cb6c81faaa067b4b05dcd152188"
        }
      ]
    }
  ]
}
