plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.6'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.project'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

ext {
    set('springModulithVersion', "2.0.6")
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.modulith:spring-modulith-starter-core'
    implementation 'org.springframework.modulith:spring-modulith-starter-jpa'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-security-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation 'org.springframework.modulith:spring-modulith-starter-test'
    testCompileOnly 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testAnnotationProcessor 'org.projectlombok:lombok'
    // Database Dependencies
    runtimeOnly 'org.postgresql:postgresql:42.7.11'
    compileOnly 'org.postgresql:postgresql:42.7.11'
    implementation 'org.postgresql:postgresql:42.7.11'
    // JWT Dependencies
    implementation 'com.nimbusds:nimbus-jose-jwt:10.9'
    runtimeOnly 'com.nimbusds:nimbus-jose-jwt:10.9'
    compileOnly 'com.nimbusds:nimbus-jose-jwt:10.9'
    testImplementation 'com.nimbusds:nimbus-jose-jwt:10.9'
    // Validation Dependencies
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    testImplementation 'org.springframework.boot:spring-boot-starter-validation-test'
    // Environment Variables Loading
    implementation 'io.github.cdimascio:dotenv-java:3.0.2'
    // Test Database
    testRuntimeOnly 'com.h2database:h2:2.3.232'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.modulith:spring-modulith-bom:${springModulithVersion}"
    }
}

tasks.named('test') {
    useJUnitPlatform()
}