{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-validation",
    "version": "4.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-validation",
          "version": {
            "requires": "4.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-validation-4.0.6.jar",
          "url": "spring-boot-starter-validation-4.0.6.jar",
          "size": 4767,
          "sha512": "655aab423d6949301b1428353f2f0dd3752eff2b9247ef060f4e551977010eb5c2ab945918865e43bafd692f9f0d1ac1b0f24f2c6b9066b12151edd3b67b06ef",
          "sha256": "31cc784d9d7ae207dd24d731890f177df8213e4abe0d627f08bf82d9e36cd952",
          "sha1": "1073fb7a768fe557bd5cc7bd26a2ed3ef08cc701",
          "md5": "2bb3d8a8b0e3796ffbadbacacceb61c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-validation",
          "version": {
            "requires": "4.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-validation-4.0.6.jar",
          "url": "spring-boot-starter-validation-4.0.6.jar",
          "size": 4767,
          "sha512": "655aab423d6949301b1428353f2f0dd3752eff2b9247ef060f4e551977010eb5c2ab945918865e43bafd692f9f0d1ac1b0f24f2c6b9066b12151edd3b67b06ef",
          "sha256": "31cc784d9d7ae207dd24d731890f177df8213e4abe0d627f08bf82d9e36cd952",
          "sha1": "1073fb7a768fe557bd5cc7bd26a2ed3ef08cc701",
          "md5": "2bb3d8a8b0e3796ffbadbacacceb61c1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-4.0.6-javadoc.jar",
          "url": "spring-boot-starter-validation-4.0.6-javadoc.jar",
          "size": 4767,
          "sha512": "655aab423d6949301b1428353f2f0dd3752eff2b9247ef060f4e551977010eb5c2ab945918865e43bafd692f9f0d1ac1b0f24f2c6b9066b12151edd3b67b06ef",
          "sha256": "31cc784d9d7ae207dd24d731890f177df8213e4abe0d627f08bf82d9e36cd952",
          "sha1": "1073fb7a768fe557bd5cc7bd26a2ed3ef08cc701",
          "md5": "2bb3d8a8b0e3796ffbadbacacceb61c1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-4.0.6-sources.jar",
          "url": "spring-boot-starter-validation-4.0.6-sources.jar",
          "size": 4767,
          "sha512": "655aab423d6949301b1428353f2f0dd3752eff2b9247ef060f4e551977010eb5c2ab945918865e43bafd692f9f0d1ac1b0f24f2c6b9066b12151edd3b67b06ef",
          "sha256": "31cc784d9d7ae207dd24d731890f177df8213e4abe0d627f08bf82d9e36cd952",
          "sha1": "1073fb7a768fe557bd5cc7bd26a2ed3ef08cc701",
          "md5": "2bb3d8a8b0e3796ffbadbacacceb61c1"
        }
      ]
    }
  ]
}
