{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-test",
    "version": "4.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.4"
          }
        },
        {
          "group": "net.minidev",
          "module": "json-smart",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.7"
          }
        },
        {
          "group": "org.awaitility",
          "module": "awaitility",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.20.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.20.0"
          }
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "7.0.7"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.10.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-4.0.6.jar",
          "url": "spring-boot-starter-test-4.0.6.jar",
          "size": 4791,
          "sha512": "41dde64ef4c35735c70211bd109cf11ff68f2275a593131749cfefa6541a603cfe0dbbd6ae6af21c5d69e22444f28e362669ef860f240d860c914535154ef4a1",
          "sha256": "7068e629a0b79c838ed454fea37c94cb1a6ac705b7c148c902e78e8fc6634b99",
          "sha1": "45552b94787c926ec41e1e20d6836a6c4d307e98",
          "md5": "4443de583b3ee1f98d7609685023d4c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.4"
          }
        },
        {
          "group": "net.minidev",
          "module": "json-smart",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.7"
          }
        },
        {
          "group": "org.awaitility",
          "module": "awaitility",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.20.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.20.0"
          }
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "7.0.7"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.10.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-4.0.6.jar",
          "url": "spring-boot-starter-test-4.0.6.jar",
          "size": 4791,
          "sha512": "41dde64ef4c35735c70211bd109cf11ff68f2275a593131749cfefa6541a603cfe0dbbd6ae6af21c5d69e22444f28e362669ef860f240d860c914535154ef4a1",
          "sha256": "7068e629a0b79c838ed454fea37c94cb1a6ac705b7c148c902e78e8fc6634b99",
          "sha1": "45552b94787c926ec41e1e20d6836a6c4d307e98",
          "md5": "4443de583b3ee1f98d7609685023d4c4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-4.0.6-javadoc.jar",
          "url": "spring-boot-starter-test-4.0.6-javadoc.jar",
          "size": 4791,
          "sha512": "41dde64ef4c35735c70211bd109cf11ff68f2275a593131749cfefa6541a603cfe0dbbd6ae6af21c5d69e22444f28e362669ef860f240d860c914535154ef4a1",
          "sha256": "7068e629a0b79c838ed454fea37c94cb1a6ac705b7c148c902e78e8fc6634b99",
          "sha1": "45552b94787c926ec41e1e20d6836a6c4d307e98",
          "md5": "4443de583b3ee1f98d7609685023d4c4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-4.0.6-sources.jar",
          "url": "spring-boot-starter-test-4.0.6-sources.jar",
          "size": 4791,
          "sha512": "41dde64ef4c35735c70211bd109cf11ff68f2275a593131749cfefa6541a603cfe0dbbd6ae6af21c5d69e22444f28e362669ef860f240d860c914535154ef4a1",
          "sha256": "7068e629a0b79c838ed454fea37c94cb1a6ac705b7c148c902e78e8fc6634b99",
          "sha1": "45552b94787c926ec41e1e20d6836a6c4d307e98",
          "md5": "4443de583b3ee1f98d7609685023d4c4"
        }
      ]
    }
  ]
}
