{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-health",
    "version": "4.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-health-4.0.6.jar",
          "url": "spring-boot-health-4.0.6.jar",
          "size": 154374,
          "sha512": "5a4ba9ee9d1d1d9e9e54d80ab64849d6ce687888f40a0ec2d0a268ec6c4003e510f97ffa4184c202558fb3ab715b2a2026028311571f781547ccfbcb7c9dd1fd",
          "sha256": "07dfd4f56995588fa6c77dc3afcb26f3559ffb34eeb9dbc729aad70fe551f0bc",
          "sha1": "992fd269677bb02b751ef1f58621abcff3855ea0",
          "md5": "548829e07d046469ec01e8f3cc3217c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-health-4.0.6.jar",
          "url": "spring-boot-health-4.0.6.jar",
          "size": 154374,
          "sha512": "5a4ba9ee9d1d1d9e9e54d80ab64849d6ce687888f40a0ec2d0a268ec6c4003e510f97ffa4184c202558fb3ab715b2a2026028311571f781547ccfbcb7c9dd1fd",
          "sha256": "07dfd4f56995588fa6c77dc3afcb26f3559ffb34eeb9dbc729aad70fe551f0bc",
          "sha1": "992fd269677bb02b751ef1f58621abcff3855ea0",
          "md5": "548829e07d046469ec01e8f3cc3217c0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-health-4.0.6-javadoc.jar",
          "url": "spring-boot-health-4.0.6-javadoc.jar",
          "size": 342819,
          "sha512": "c37748023093070273f7c8097ef8945d4a841783385e38f0df0d63f7095c1f0c317fdf406925cfc4321bbdb278c16bc61f3ba63c38eb63556df5a1c3a3f6a42b",
          "sha256": "c315f40cde774ca753da26b9dea49d46a5c8d6f8f23ac71a450816936f9c94d9",
          "sha1": "184ce1b961ce7ba9ef953cd6a338dc5cb7668e66",
          "md5": "e2a2325af10d6dba23db9b39b89d54f9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-health-4.0.6-sources.jar",
          "url": "spring-boot-health-4.0.6-sources.jar",
          "size": 116295,
          "sha512": "32cb788e7d460f74344595f7a35e2c8f72fdca58f1b7b89033f2cbe83df64bff6148ca813b56f36ab735e758f9f79531a7854d859ac30ad21200c9f5e8b7f874",
          "sha256": "b1fe48efc61f989012a039756e088770d1ce707707b2ec83ac65259ce31c0d29",
          "sha1": "c0f3c908c358063b01612a9dd7c04f215c5247c3",
          "md5": "69903100cc0e596539e5e5e2d9ba135a"
        }
      ]
    }
  ]
}
