{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat-runtime",
    "version": "4.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-tomcat",
          "version": {
            "requires": "4.0.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-web-server",
          "version": {
            "requires": "4.0.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "11.0.21"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "11.0.21"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "11.0.21"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-runtime-4.0.6.jar",
          "url": "spring-boot-starter-tomcat-runtime-4.0.6.jar",
          "size": 4745,
          "sha512": "7d486f480b003097428ac950292a6c8404d1b2c50cc6c51d28245b7f9d3d2f093dfc15976091e7b1a2da71560bd030c751c10d8d9b5ca1881092ecb6b5bed198",
          "sha256": "caab936e904edcee854791178ad5ad3018862c35a376d27f1e5802681a88429f",
          "sha1": "93cb616795ce25f7fd58ef3d1dcc8c3ed2d82578",
          "md5": "761cf315d62c92a49f008daf109b8327"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-tomcat",
          "version": {
            "requires": "4.0.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-web-server",
          "version": {
            "requires": "4.0.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "11.0.21"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "11.0.21"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "11.0.21"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-runtime-4.0.6.jar",
          "url": "spring-boot-starter-tomcat-runtime-4.0.6.jar",
          "size": 4745,
          "sha512": "7d486f480b003097428ac950292a6c8404d1b2c50cc6c51d28245b7f9d3d2f093dfc15976091e7b1a2da71560bd030c751c10d8d9b5ca1881092ecb6b5bed198",
          "sha256": "caab936e904edcee854791178ad5ad3018862c35a376d27f1e5802681a88429f",
          "sha1": "93cb616795ce25f7fd58ef3d1dcc8c3ed2d82578",
          "md5": "761cf315d62c92a49f008daf109b8327"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-runtime-4.0.6-javadoc.jar",
          "url": "spring-boot-starter-tomcat-runtime-4.0.6-javadoc.jar",
          "size": 4745,
          "sha512": "7d486f480b003097428ac950292a6c8404d1b2c50cc6c51d28245b7f9d3d2f093dfc15976091e7b1a2da71560bd030c751c10d8d9b5ca1881092ecb6b5bed198",
          "sha256": "caab936e904edcee854791178ad5ad3018862c35a376d27f1e5802681a88429f",
          "sha1": "93cb616795ce25f7fd58ef3d1dcc8c3ed2d82578",
          "md5": "761cf315d62c92a49f008daf109b8327"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-runtime-4.0.6-sources.jar",
          "url": "spring-boot-starter-tomcat-runtime-4.0.6-sources.jar",
          "size": 4745,
          "sha512": "7d486f480b003097428ac950292a6c8404d1b2c50cc6c51d28245b7f9d3d2f093dfc15976091e7b1a2da71560bd030c751c10d8d9b5ca1881092ecb6b5bed198",
          "sha256": "caab936e904edcee854791178ad5ad3018862c35a376d27f1e5802681a88429f",
          "sha1": "93cb616795ce25f7fd58ef3d1dcc8c3ed2d82578",
          "md5": "761cf315d62c92a49f008daf109b8327"
        }
      ]
    }
  ]
}
