spring.application.name=flow

# Server configuration
server.port=3002

# Management endpoint configuration
management.endpoint.health.show-details=always

server.servlet.context-path=/api/v1

# Database configuration
spring.datasource.url=jdbc:postgresql://db.vutlxufqxwhpgkmacvlu.supabase.co:5432/postgres?user=postgres&password=Zaid@530flow
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Zaid@530flow
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Spring Modulith configuration
spring.modulith.enabled=false
