{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-micrometer-metrics",
    "version": "4.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-micrometer-metrics",
          "version": {
            "requires": "4.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-micrometer-metrics-4.0.6.jar",
          "url": "spring-boot-starter-micrometer-metrics-4.0.6.jar",
          "size": 4748,
          "sha512": "093ab16405c515f6fb4ccec420b072109f4ab67de80a28bbd9b1ba77c8f0c47380844b6516145c70af4c6247200d882b1ddbe0617d361eedc730b313045ba2ca",
          "sha256": "7e3da1a9dadad54e088bd764d4bfc6af0611ad52ee0593266fbd49a6946d2008",
          "sha1": "fb1dcfc7713f6279ce3919c5a81008632d901594",
          "md5": "9aab5532cb4fe08ff59f9e43a8ffb908"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-micrometer-metrics",
          "version": {
            "requires": "4.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-micrometer-metrics-4.0.6.jar",
          "url": "spring-boot-starter-micrometer-metrics-4.0.6.jar",
          "size": 4748,
          "sha512": "093ab16405c515f6fb4ccec420b072109f4ab67de80a28bbd9b1ba77c8f0c47380844b6516145c70af4c6247200d882b1ddbe0617d361eedc730b313045ba2ca",
          "sha256": "7e3da1a9dadad54e088bd764d4bfc6af0611ad52ee0593266fbd49a6946d2008",
          "sha1": "fb1dcfc7713f6279ce3919c5a81008632d901594",
          "md5": "9aab5532cb4fe08ff59f9e43a8ffb908"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-micrometer-metrics-4.0.6-javadoc.jar",
          "url": "spring-boot-starter-micrometer-metrics-4.0.6-javadoc.jar",
          "size": 4748,
          "sha512": "093ab16405c515f6fb4ccec420b072109f4ab67de80a28bbd9b1ba77c8f0c47380844b6516145c70af4c6247200d882b1ddbe0617d361eedc730b313045ba2ca",
          "sha256": "7e3da1a9dadad54e088bd764d4bfc6af0611ad52ee0593266fbd49a6946d2008",
          "sha1": "fb1dcfc7713f6279ce3919c5a81008632d901594",
          "md5": "9aab5532cb4fe08ff59f9e43a8ffb908"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-micrometer-metrics-4.0.6-sources.jar",
          "url": "spring-boot-starter-micrometer-metrics-4.0.6-sources.jar",
          "size": 4748,
          "sha512": "093ab16405c515f6fb4ccec420b072109f4ab67de80a28bbd9b1ba77c8f0c47380844b6516145c70af4c6247200d882b1ddbe0617d361eedc730b313045ba2ca",
          "sha256": "7e3da1a9dadad54e088bd764d4bfc6af0611ad52ee0593266fbd49a6946d2008",
          "sha1": "fb1dcfc7713f6279ce3919c5a81008632d901594",
          "md5": "9aab5532cb4fe08ff59f9e43a8ffb908"
        }
      ]
    }
  ]
}
