{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-actuator",
    "version": "4.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-micrometer-metrics",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-actuator-autoconfigure",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-health",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.16.5"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-jakarta9",
          "version": {
            "requires": "1.16.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-actuator-4.0.6.jar",
          "url": "spring-boot-starter-actuator-4.0.6.jar",
          "size": 4805,
          "sha512": "37f6c496e0124e6a247c1daa39c3dec2f6ad29cd57ec19042372e84b8c3457b0f8c2e85830dcf5cd8fe5ab1cac4d9c09700dd8ad5358631155cbb521cd17d051",
          "sha256": "e1dc79923bc2815acc4dc88c985715534910af567df707f75b96cca2ed692a85",
          "sha1": "a225366838915974c39449e201de012d4d88a609",
          "md5": "bba1a3017f9c6922ac3f5bc692b669fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-micrometer-metrics",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-actuator-autoconfigure",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-health",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.16.5"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-jakarta9",
          "version": {
            "requires": "1.16.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-actuator-4.0.6.jar",
          "url": "spring-boot-starter-actuator-4.0.6.jar",
          "size": 4805,
          "sha512": "37f6c496e0124e6a247c1daa39c3dec2f6ad29cd57ec19042372e84b8c3457b0f8c2e85830dcf5cd8fe5ab1cac4d9c09700dd8ad5358631155cbb521cd17d051",
          "sha256": "e1dc79923bc2815acc4dc88c985715534910af567df707f75b96cca2ed692a85",
          "sha1": "a225366838915974c39449e201de012d4d88a609",
          "md5": "bba1a3017f9c6922ac3f5bc692b669fb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-actuator-4.0.6-javadoc.jar",
          "url": "spring-boot-starter-actuator-4.0.6-javadoc.jar",
          "size": 4805,
          "sha512": "37f6c496e0124e6a247c1daa39c3dec2f6ad29cd57ec19042372e84b8c3457b0f8c2e85830dcf5cd8fe5ab1cac4d9c09700dd8ad5358631155cbb521cd17d051",
          "sha256": "e1dc79923bc2815acc4dc88c985715534910af567df707f75b96cca2ed692a85",
          "sha1": "a225366838915974c39449e201de012d4d88a609",
          "md5": "bba1a3017f9c6922ac3f5bc692b669fb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-actuator-4.0.6-sources.jar",
          "url": "spring-boot-starter-actuator-4.0.6-sources.jar",
          "size": 4805,
          "sha512": "37f6c496e0124e6a247c1daa39c3dec2f6ad29cd57ec19042372e84b8c3457b0f8c2e85830dcf5cd8fe5ab1cac4d9c09700dd8ad5358631155cbb521cd17d051",
          "sha256": "e1dc79923bc2815acc4dc88c985715534910af567df707f75b96cca2ed692a85",
          "sha1": "a225366838915974c39449e201de012d4d88a609",
          "md5": "bba1a3017f9c6922ac3f5bc692b669fb"
        }
      ]
    }
  ]
}
