{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-actuator",
    "version": "4.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-actuator-4.0.6.jar",
          "url": "spring-boot-actuator-4.0.6.jar",
          "size": 357012,
          "sha512": "168c94706e3de159b177837bffb2da6b2e558bdc50f313dcbb3818315f8d948009fcc9e11b644877748934ea6fe6827a93a37557517a80cf5b095b4d9253941f",
          "sha256": "c5b4902053c61923d81e6fae9864f396dd5ada923e145bc338057b3abf0f1ed4",
          "sha1": "0e5470926718d2c85f574eff0f0f1f264a605a7f",
          "md5": "a43c3f93cbbc73e77d0fdc2c2b578c77"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-actuator-4.0.6.jar",
          "url": "spring-boot-actuator-4.0.6.jar",
          "size": 357012,
          "sha512": "168c94706e3de159b177837bffb2da6b2e558bdc50f313dcbb3818315f8d948009fcc9e11b644877748934ea6fe6827a93a37557517a80cf5b095b4d9253941f",
          "sha256": "c5b4902053c61923d81e6fae9864f396dd5ada923e145bc338057b3abf0f1ed4",
          "sha1": "0e5470926718d2c85f574eff0f0f1f264a605a7f",
          "md5": "a43c3f93cbbc73e77d0fdc2c2b578c77"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-actuator-4.0.6-javadoc.jar",
          "url": "spring-boot-actuator-4.0.6-javadoc.jar",
          "size": 850354,
          "sha512": "3266ef13ee293036db54475e57e0cbbe83a3a4cccd5adae873367e8dffcd3927216f4ff194d7e081ee03a60ee3529a925290535d07ffb85487e45983941998ef",
          "sha256": "ac83a337c0a447b83e55c6656ef18f26cf103d141d0c1c8bbf2da9e08d8a40cf",
          "sha1": "95206af74e77fc934ff3b15b4624e12c546dbb10",
          "md5": "159dd0e9dfe4e33eb0fec6392b43f5d9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-actuator-4.0.6-sources.jar",
          "url": "spring-boot-actuator-4.0.6-sources.jar",
          "size": 243003,
          "sha512": "f96e88b583f5bd018a44bc0506d09f8c5120bed839a9422d2ba4a265c6e339c826927b740be9c4d9f40192ac14c284c748303a1b669ec1c42162325871f703f0",
          "sha256": "9e63e208868b807c24ffb2c8f4216e9e35bc2f231a6afe51e89cf087e861913e",
          "sha1": "fedbaf473ceb3cc7ac5129003c0b4dfb796db3fe",
          "md5": "bc99856916dc8512ab1924de9d7fd391"
        }
      ]
    }
  ]
}
