{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-micrometer-observation",
    "version": "4.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.16.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-micrometer-observation-4.0.6.jar",
          "url": "spring-boot-micrometer-observation-4.0.6.jar",
          "size": 28846,
          "sha512": "9aa92c7d05989b2d1297b2b0ec3b1744fdc90632b54b944a53fdc6387edaa36d2ec17578633afe81fb03399bf34a24ed4a51049955c0a339bf49a67b8a1532f6",
          "sha256": "3684b47955ab80ba796918a07610b7957f4a66366c3b67b51bf8eb4cdc6df7f6",
          "sha1": "ab486802d7623d00f02ee9838d94af66636b440c",
          "md5": "785b644088878e6e9d96f228362e932d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.16.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-micrometer-observation-4.0.6.jar",
          "url": "spring-boot-micrometer-observation-4.0.6.jar",
          "size": 28846,
          "sha512": "9aa92c7d05989b2d1297b2b0ec3b1744fdc90632b54b944a53fdc6387edaa36d2ec17578633afe81fb03399bf34a24ed4a51049955c0a339bf49a67b8a1532f6",
          "sha256": "3684b47955ab80ba796918a07610b7957f4a66366c3b67b51bf8eb4cdc6df7f6",
          "sha1": "ab486802d7623d00f02ee9838d94af66636b440c",
          "md5": "785b644088878e6e9d96f228362e932d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-micrometer-observation-4.0.6-javadoc.jar",
          "url": "spring-boot-micrometer-observation-4.0.6-javadoc.jar",
          "size": 135670,
          "sha512": "e8cc966406712b986d2d4926fda670cd3fb4bf790fb08d993a74f1c1030e24373945d644a93c5e9e32661497d4691ad4ae426d34fc2934583c624f5dd71c5834",
          "sha256": "0f966fba94180e4f781c930d983b95b106519ab597137f0181398476dee8675b",
          "sha1": "f9b9ddbbcd5209f817dc581762d0fbcdd0414aa0",
          "md5": "93aca42379d7a08934e0f23d5095674c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-micrometer-observation-4.0.6-sources.jar",
          "url": "spring-boot-micrometer-observation-4.0.6-sources.jar",
          "size": 19810,
          "sha512": "bd2faeb364421df4d51b42b9da26bb0b80765412010f434f435a8b05e04bbe476ca870d60fed3be55fa836d60762359ad64ce1c6554d173aad37071a3dd93613",
          "sha256": "321bfd25a7aee2f8ba353508c31cf7f5cbb3079e2a2d03e500d5a540668468af",
          "sha1": "07c4e4b456fd0f540b4f23a78841f48b0114a3c1",
          "md5": "7b024a1a84bfd205daa343557caa22da"
        }
      ]
    }
  ]
}
