{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-jackson",
    "version": "4.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-jackson",
          "version": {
            "requires": "4.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-jackson-4.0.6.jar",
          "url": "spring-boot-starter-jackson-4.0.6.jar",
          "size": 4741,
          "sha512": "62271c77cba370fd4097ff610990af7864f00dbd379abe63076a352f3c130a5f8baac45cc82ec00173fd3368201d167fb58b8e7f00870fbb69e384be99145824",
          "sha256": "78a3fbce32e41b9185a3ea32275f494529ace99578f3ec105b2fa03df2043e83",
          "sha1": "38895733cded8ac4007d7ee028e3bf1f718514f1",
          "md5": "d4c1976bb6219347c944d77c79c4de73"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-jackson",
          "version": {
            "requires": "4.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-jackson-4.0.6.jar",
          "url": "spring-boot-starter-jackson-4.0.6.jar",
          "size": 4741,
          "sha512": "62271c77cba370fd4097ff610990af7864f00dbd379abe63076a352f3c130a5f8baac45cc82ec00173fd3368201d167fb58b8e7f00870fbb69e384be99145824",
          "sha256": "78a3fbce32e41b9185a3ea32275f494529ace99578f3ec105b2fa03df2043e83",
          "sha1": "38895733cded8ac4007d7ee028e3bf1f718514f1",
          "md5": "d4c1976bb6219347c944d77c79c4de73"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-jackson-4.0.6-javadoc.jar",
          "url": "spring-boot-starter-jackson-4.0.6-javadoc.jar",
          "size": 4741,
          "sha512": "62271c77cba370fd4097ff610990af7864f00dbd379abe63076a352f3c130a5f8baac45cc82ec00173fd3368201d167fb58b8e7f00870fbb69e384be99145824",
          "sha256": "78a3fbce32e41b9185a3ea32275f494529ace99578f3ec105b2fa03df2043e83",
          "sha1": "38895733cded8ac4007d7ee028e3bf1f718514f1",
          "md5": "d4c1976bb6219347c944d77c79c4de73"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-jackson-4.0.6-sources.jar",
          "url": "spring-boot-starter-jackson-4.0.6-sources.jar",
          "size": 4741,
          "sha512": "62271c77cba370fd4097ff610990af7864f00dbd379abe63076a352f3c130a5f8baac45cc82ec00173fd3368201d167fb58b8e7f00870fbb69e384be99145824",
          "sha256": "78a3fbce32e41b9185a3ea32275f494529ace99578f3ec105b2fa03df2043e83",
          "sha1": "38895733cded8ac4007d7ee028e3bf1f718514f1",
          "md5": "d4c1976bb6219347c944d77c79c4de73"
        }
      ]
    }
  ]
}
