{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "4.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-4.0.6.jar",
          "url": "spring-boot-starter-4.0.6.jar",
          "size": 4768,
          "sha512": "54b4e26fac275226f3d643e1ec869d23ba9441bdc070106154bffb62aae6b6bff1e2df163901a717bc8a42e14545f93131811a14de0099bbb1be942c4f68f829",
          "sha256": "4cb0ed1cf253aa93b6e80a39d69e68a48ff4a01d60c3c127533132b46bdb790a",
          "sha1": "589f058443a5ca53cf38253fa05aa69dd0e87e0e",
          "md5": "e7e5a05d3033c43df32dccc61368016f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-4.0.6.jar",
          "url": "spring-boot-starter-4.0.6.jar",
          "size": 4768,
          "sha512": "54b4e26fac275226f3d643e1ec869d23ba9441bdc070106154bffb62aae6b6bff1e2df163901a717bc8a42e14545f93131811a14de0099bbb1be942c4f68f829",
          "sha256": "4cb0ed1cf253aa93b6e80a39d69e68a48ff4a01d60c3c127533132b46bdb790a",
          "sha1": "589f058443a5ca53cf38253fa05aa69dd0e87e0e",
          "md5": "e7e5a05d3033c43df32dccc61368016f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-4.0.6-javadoc.jar",
          "url": "spring-boot-starter-4.0.6-javadoc.jar",
          "size": 4768,
          "sha512": "54b4e26fac275226f3d643e1ec869d23ba9441bdc070106154bffb62aae6b6bff1e2df163901a717bc8a42e14545f93131811a14de0099bbb1be942c4f68f829",
          "sha256": "4cb0ed1cf253aa93b6e80a39d69e68a48ff4a01d60c3c127533132b46bdb790a",
          "sha1": "589f058443a5ca53cf38253fa05aa69dd0e87e0e",
          "md5": "e7e5a05d3033c43df32dccc61368016f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-4.0.6-sources.jar",
          "url": "spring-boot-starter-4.0.6-sources.jar",
          "size": 4768,
          "sha512": "54b4e26fac275226f3d643e1ec869d23ba9441bdc070106154bffb62aae6b6bff1e2df163901a717bc8a42e14545f93131811a14de0099bbb1be942c4f68f829",
          "sha256": "4cb0ed1cf253aa93b6e80a39d69e68a48ff4a01d60c3c127533132b46bdb790a",
          "sha1": "589f058443a5ca53cf38253fa05aa69dd0e87e0e",
          "md5": "e7e5a05d3033c43df32dccc61368016f"
        }
      ]
    }
  ]
}
