{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-micrometer-metrics",
    "version": "4.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-micrometer-observation",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.16.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-micrometer-metrics-4.0.6.jar",
          "url": "spring-boot-micrometer-metrics-4.0.6.jar",
          "size": 240910,
          "sha512": "a3b521433bf86d9fff0df1806cbffee8f01cd6973bcc78c09227b90e3eb0a561c1435813462bf1c77890e180c4a15a96b185f32b687c4deb9cd431a0e00f7c39",
          "sha256": "a21e1e415c1e6ab3252b3745110f0717e602cb6b1ffa59d2f2a29bc3ab45bdb0",
          "sha1": "96dbcd4eab73a4fcb2e277c6416d2c0758132689",
          "md5": "b420e53496f245cb3371299cee305b31"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-micrometer-observation",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.16.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-micrometer-metrics-4.0.6.jar",
          "url": "spring-boot-micrometer-metrics-4.0.6.jar",
          "size": 240910,
          "sha512": "a3b521433bf86d9fff0df1806cbffee8f01cd6973bcc78c09227b90e3eb0a561c1435813462bf1c77890e180c4a15a96b185f32b687c4deb9cd431a0e00f7c39",
          "sha256": "a21e1e415c1e6ab3252b3745110f0717e602cb6b1ffa59d2f2a29bc3ab45bdb0",
          "sha1": "96dbcd4eab73a4fcb2e277c6416d2c0758132689",
          "md5": "b420e53496f245cb3371299cee305b31"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-micrometer-metrics-4.0.6-javadoc.jar",
          "url": "spring-boot-micrometer-metrics-4.0.6-javadoc.jar",
          "size": 528636,
          "sha512": "c4c57e56d91d670ca23ab503690df77ca9a32295d86b01bf27724b35dcee2fba9908d14b02b1361b59b108981108ccb7d1b66ab3fea2d55e449d0663a44eb0a2",
          "sha256": "f78b4a95cad5fca87e8be74cb979a4f42f6b54562ad4a7947ff9293fc23476ca",
          "sha1": "fa0daae83288f9fe4dd77961960d9f8c9e81cc8e",
          "md5": "54014e875b450515ab2cd27ac45dde12"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-micrometer-metrics-4.0.6-sources.jar",
          "url": "spring-boot-micrometer-metrics-4.0.6-sources.jar",
          "size": 169116,
          "sha512": "b4b5bae8bdf4175a10abd469dbc937875bbe74db0f290b2a50fe283ee1f6f8d7f5e2fba510dd3220125234d059da24f756e7170c8c2f14d2c323ff18fe1c09bb",
          "sha256": "9aed3e6fef953ead1dbe41033a39c67b4d1798a6d866099195f41280e11250ff",
          "sha1": "391b19ac41786debc37cf0c29e803ffaaa4f8f5e",
          "md5": "5b6b239ae4ea3135f8f5d45a15f27d83"
        }
      ]
    }
  ]
}
